project:
    logo: /gkide.png
    name: HackerMatrix theme
    description: HackerMatrix is a theme for Jekyll!
    repository: gkide

collections:
    docs:
        output: true
        permalink: /docs/:path/
    posts:
        output: true
        permalink: /:categories/:year/:month/:day/:title/

destination: build

exclude:
    - script/
    - README.md

plugins:
    - jemoji
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-sitemap
    - jekyll-mentions
    - jekyll-github-metadata

#sass:
#    style: compressed

remote_theme: HackerMatrix
